{% set name = "jupyterlab-python-file" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 556377c1896c1ebf37bd6e9f7ad363c627b4472f82f59ca5fe2adf6daf44dc63

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - nodejs
    - jupyter-packaging
    - jupyterlab >=3.0.0rc4
  run:
    - python >=3.6
    - jupyterlab >=3.0.0rc4

test:
  commands:
    - jupyter labextension list 2>&1 | grep -ie "jupyterlab-python-file.*enabled.*ok" -

about:
  home: https://github.com/jtpio/jupyterlab-python-file
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Create Python Files from JupyterLab

  description: |
    Create Python Files from JupyterLab
  dev_url: https://github.com/jtpio/jupyterlab-python-file

extra:
  recipe-maintainers:
    - jtpio
